name: Build and release binaries

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git REF to use for manual pre-release"
        required: true
        type: string
      prerelease_suffix:
        description: "Suffix which has been used for manual pre-release name"
        required: false
        type: string
        default: "notag"
      release_macos_amd64:
        description: "Release for MacOS amd64?"
        required: false
        type: boolean
        default: true
      release_macos_arm64:
        description: "Release for MacOS arm64?"
        required: false
        type: boolean
        default: true
      release_linux_amd64:
        description: "Release for Linux amd64?"
        required: false
        type: boolean
        default: true
      release_linux_arm64:
        description: "Release for Linux arm64?"
        required: false
        type: boolean
        default: true
      release_windows_amd64:
        description: "Release for Windows amd64?"
        required: false
        type: boolean
        default: true
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "MacOS x86"
            runner: macos-12-large
            release-suffix: macosx-amd64
            required: ${{ github.event.inputs.release_macos_amd64 || true }}
          - name: "MacOS arm64"
            runner: [self-hosted, macOS, ARM64]
            release-suffix: macosx-arm64
            required: ${{ github.event.inputs.release_macos_arm64 || true }}
          - name: "Linux x86"
            runner: matterlabs-ci-runner
            image: matterlabs/llvm_runner:ubuntu22-llvm15-latest
            target: "x86_64-unknown-linux-musl"
            release-suffix: linux-amd64
            required: ${{ github.event.inputs.release_linux_amd64 || true }}
          - name: "Linux ARM64"
            runner: matterlabs-ci-runner-arm
            image: matterlabs/llvm_runner:ubuntu22-llvm15-latest
            target: "aarch64-unknown-linux-musl"
            rustflags: "-C link-arg=-Wl,-Bstatic -C link-arg=-lc -C link-arg=-L/usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/ -C link-arg=-lclang_rt.builtins-aarch64"
            release-suffix: linux-arm64
            required: ${{ github.event.inputs.release_linux_arm64 || true }}
          - name: "Windows"
            runner: windows-2022-github-hosted-16core
            shell: 'msys2 {0}'
            release-suffix: windows-amd64-gnu
            required: ${{ github.event.inputs.release_windows_amd64 || true }}
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image || '' }} # Special workaround to allow matrix builds with optional container
    name: ${{ matrix.name }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build LLVM
        uses: ./.github/actions/build-llvm
        with:
          target: ${{ matrix.target }}
      - name: Build zkvyper
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
          rustflags: ${{ matrix.rustflags }}
      - name: Prepare binary
        shell: ${{ matrix.shell || 'bash' }}
        run: |
          mkdir -p ./releases/${RELEASE_SUFFIX}
          strip ./target/${{ matrix.target }}/release/zkvyper
          [ ! -z "$GITHUB_REF_NAME" ] && TAG_SUFFIX="-${GITHUB_REF_NAME}"
          [ "$RUNNER_OS" = "Windows" ] && WIN_SUFFIX=".exe"
          mv ./target/${{ matrix.target }}/release/zkvyper${WIN_SUFFIX} \
            ./releases/${RELEASE_SUFFIX}/zkvyper-${RELEASE_SUFFIX}${TAG_SUFFIX}${WIN_SUFFIX}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.release-suffix }}
          path: releases

  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || '' }}

      - name: Download MacOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          pattern: release*
          path: releases

      - name: Checkout repo with binaries
        if: github.ref_type == 'tag'
        uses: actions/checkout@v4
        with:
          repository: matter-labs/zkvyper-bin
          path: public_repo
          ref: main

      - name: Generate Version or SHA
        id: version_or_sha
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git config --global --add safe.directory $GITHUB_WORKSPACE
            echo "version_or_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          else
            echo "version_or_sha=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: List binaries to be released
        run: tree ./releases

      - name: Publish pre-release
        if: github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            BINARIES=($(find ./releases -type f))
            gh release create \
              --prerelease prerelease-${{ steps.version_or_sha.outputs.version_or_sha }}-${{ github.event.inputs.prerelease_suffix }} \
              --target ${{ github.event.inputs.ref }} \
              --title prerelease-${{ steps.version_or_sha.outputs.version_or_sha }}-${{ github.event.inputs.prerelease_suffix }} \
              "${BINARIES[@]}"

      - name: Publish release (this repository)
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            BINARIES=($(find ./releases -type f))
            gh release create ${{ steps.version_or_sha.outputs.version_or_sha }} \
              --title ${{ steps.version_or_sha.outputs.version_or_sha }} \
              "${BINARIES[@]}"
